"""Add test column to sheet_names 

Revision ID: 42addd044bae
Revises: b34a8d096143
Create Date: 2024-06-22 14:32:59.630620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42addd044bae'
down_revision: Union[str, None] = 'b34a8d096143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_names', sa.Column('test', sa.String(), nullable=True))
    op.drop_column('templates', 'smoking_cessation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('smoking_cessation', sa.BOOLEAN(), nullable=True))
    op.drop_column('sheet_names', 'test')
    # ### end Alembic commands ###
