"""Remove test column from SheetName

Revision ID: b352c0ad09f4
Revises: 42addd044bae
Create Date: 2024-06-22 14:41:58.908685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b352c0ad09f4'
down_revision: Union[str, None] = '42addd044bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_names', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_names', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
